var hierarchy =
[
    [ "memory::allocator_base", "classmemory_1_1allocator__base.html", [
      [ "memory::block_allocator", "classmemory_1_1block__allocator.html", null ],
      [ "memory::default_allocator", "classmemory_1_1default__allocator.html", null ]
    ] ],
    [ "psl::serialization::details::anonymous_property< T >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< bool >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< const_str(\"MODE\", 4) >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::data::framebuffer_t::attachment::description >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::attachment::load_op >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::attachment::store_op >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::binding_type >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::blend_factor >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::blend_op >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::border_color >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::buffering >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::clear_value >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::compare_op >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::component_bits >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::cullmode >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::filter >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::format_t >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::image::layout >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::image_aspect >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::image_type >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::image_usage >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::memory_property >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::memory_usage >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::memory_write_frequency >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::sampler_address_mode >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::sampler_mipmap_mode >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::shader_stage >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< core::gfx::surface_mode >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< dependency >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< float >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< gfx::shader_stage >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< psl::array< attribute > >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< psl::array< binding > >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< psl::array< core::data::material_t::blendstate > >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< psl::array< descriptor > >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< psl::array< float > >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< psl::array< member > >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< psl::array< psl::string8_t > >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< psl::array< stage > >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< psl::string >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< psl::string8_t >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< psl::UID >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< std::unordered_map< psl::string, core::stream > >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< std::vector< core::data::framebuffer_t::attachment > >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< std::vector< index_size_t > >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< std::vector< psl::string8_t > >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< type >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< uint32_t >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "psl::serialization::details::anonymous_property< uint8_t >", "classpsl_1_1serialization_1_1details_1_1anonymous__property.html", null ],
    [ "core::data::framebuffer_t::attachment", "classcore_1_1data_1_1framebuffer__t_1_1attachment.html", null ],
    [ "core::ivk::framebuffer_t::binding", "structcore_1_1ivk_1_1framebuffer__t_1_1binding.html", null ],
    [ "core::data::material_t::blendstate", "classcore_1_1data_1_1material__t_1_1blendstate.html", null ],
    [ "core::ivk::buffer_t", "classcore_1_1ivk_1_1buffer__t.html", null ],
    [ "core::data::buffer_t", "classcore_1_1data_1_1buffer__t.html", null ],
    [ "core::gfx::bundle", "classcore_1_1gfx_1_1bundle.html", null ],
    [ "core::data::clear_value", "classcore_1_1data_1_1clear__value.html", null ],
    [ "core::gfx::commit_instruction", "structcore_1_1gfx_1_1commit__instruction.html", null ],
    [ "psl::ecs::details::component_info", "classpsl_1_1ecs_1_1details_1_1component__info.html", null ],
    [ "core::igles::compute", "classcore_1_1igles_1_1compute.html", null ],
    [ "core::gfx::computepass", "classcore_1_1gfx_1_1computepass.html", null ],
    [ "core::data::geometry_t::constants", "structcore_1_1data_1_1geometry__t_1_1constants.html", null ],
    [ "psl::spmc::consumer< T >", "classpsl_1_1spmc_1_1consumer.html", null ],
    [ "psl::spmc::consumer< psl::view_ptr< details::packet > >", "classpsl_1_1spmc_1_1consumer.html", null ],
    [ "core::ivk::context", "classcore_1_1ivk_1_1context.html", null ],
    [ "core::gfx::details::instance::data", "classcore_1_1gfx_1_1details_1_1instance_1_1data.html", null ],
    [ "utility::debug", "classutility_1_1debug.html", null ],
    [ "psl::ecs::details::dependency_pack", "classpsl_1_1ecs_1_1details_1_1dependency__pack.html", null ],
    [ "core::data::framebuffer_t::attachment::description", "classcore_1_1data_1_1framebuffer__t_1_1attachment_1_1description.html", null ],
    [ "utility::platform::directory", "classutility_1_1platform_1_1directory.html", null ],
    [ "core::gfx::drawgroup", "classcore_1_1gfx_1_1drawgroup.html", null ],
    [ "core::ivk::drawpass", "classcore_1_1ivk_1_1drawpass.html", null ],
    [ "psl::ecs::empty< T >", "structpsl_1_1ecs_1_1empty.html", null ],
    [ "psl::ecs::except< Ts >", "structpsl_1_1ecs_1_1except.html", null ],
    [ "psl::meta::file", "classpsl_1_1meta_1_1file.html", [
      [ "core::meta::shader", "classcore_1_1meta_1_1shader.html", null ],
      [ "core::meta::texture_t", "classcore_1_1meta_1_1texture__t.html", null ]
    ] ],
    [ "psl::ecs::filter< Ts >", "structpsl_1_1ecs_1_1filter.html", null ],
    [ "core::ivk::framebuffer_t", "classcore_1_1ivk_1_1framebuffer__t.html", null ],
    [ "core::data::framebuffer_t", "classcore_1_1data_1_1framebuffer__t.html", null ],
    [ "psl::ecs::full", "structpsl_1_1ecs_1_1full.html", null ],
    [ "core::ivk::geometry_t", "classcore_1_1ivk_1_1geometry__t.html", null ],
    [ "core::data::geometry_t", "classcore_1_1data_1_1geometry__t.html", null ],
    [ "core::ecs::systems::debug::grid", "classcore_1_1ecs_1_1systems_1_1debug_1_1grid.html", null ],
    [ "core::resource::handle< T >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< buffer_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::data::buffer_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::data::framebuffer_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::data::geometry_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::data::material_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::data::sampler_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::data::window >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::buffer_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::bundle >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::compute >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::context >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::geometry_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::material_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::shader_buffer_binding >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::gfx::texture_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::igles::buffer_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::igles::context >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::igles::program >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::igles::sampler_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::igles::shader >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::ivk::buffer_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::ivk::context >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::ivk::framebuffer_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::ivk::pipeline >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::ivk::pipeline_cache >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::ivk::sampler_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::ivk::shader >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::ivk::swapchain >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::ivk::texture_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< core::os::surface >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< framebuffer_t >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< program >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::resource::handle< swapchain >", "classcore_1_1resource_1_1handle.html", null ],
    [ "core::systems::input", "classcore_1_1systems_1_1input.html", null ],
    [ "psl::meta::library", "classpsl_1_1meta_1_1library.html", null ],
    [ "core::ivk::material_t", "classcore_1_1ivk_1_1material__t.html", null ],
    [ "core::data::material_t", "classcore_1_1data_1_1material__t.html", null ],
    [ "core::resource::metadata", "structcore_1_1resource_1_1metadata.html", null ],
    [ "core::systems::input::mouse_coordinate", "structcore_1_1systems_1_1input_1_1mouse__coordinate.html", null ],
    [ "core::systems::input::mouse_delta", "structcore_1_1systems_1_1input_1_1mouse__delta.html", null ],
    [ "psl::ecs::on_add< Ts >", "structpsl_1_1ecs_1_1on__add.html", null ],
    [ "psl::ecs::on_break< Ts >", "structpsl_1_1ecs_1_1on__break.html", null ],
    [ "psl::ecs::on_combine< Ts >", "structpsl_1_1ecs_1_1on__combine.html", null ],
    [ "psl::ecs::on_remove< Ts >", "structpsl_1_1ecs_1_1on__remove.html", null ],
    [ "utility::platform::os", "classutility_1_1platform_1_1os.html", null ],
    [ "psl::ecs::pack< Ts >", "classpsl_1_1ecs_1_1pack.html", null ],
    [ "psl::ecs::partial", "structpsl_1_1ecs_1_1partial.html", null ],
    [ "core::ivk::pipeline", "classcore_1_1ivk_1_1pipeline.html", null ],
    [ "core::ivk::pipeline_cache", "classcore_1_1ivk_1_1pipeline__cache.html", null ],
    [ "core::ivk::pipeline_key", "structcore_1_1ivk_1_1pipeline__key.html", null ],
    [ "psl::serialization::polymorphic< T >", "classpsl_1_1serialization_1_1polymorphic.html", null ],
    [ "psl::spmc::producer< T >", "classpsl_1_1spmc_1_1producer.html", null ],
    [ "psl::spmc::producer< psl::view_ptr< details::packet > >", "classpsl_1_1spmc_1_1producer.html", null ],
    [ "memory::range_t", "classmemory_1_1range__t.html", null ],
    [ "memory::region", "classmemory_1_1region.html", null ],
    [ "core::ivk::sampler_t", "classcore_1_1ivk_1_1sampler__t.html", null ],
    [ "core::data::sampler_t", "classcore_1_1data_1_1sampler__t.html", null ],
    [ "core::systems::input::scroll_delta", "structcore_1_1systems_1_1input_1_1scroll__delta.html", null ],
    [ "memory::segment", "classmemory_1_1segment.html", null ],
    [ "core::ivk::shader", "classcore_1_1ivk_1_1shader.html", null ],
    [ "psl::sparse_array< T, Key, chunks_size >", "classpsl_1_1sparse__array.html", null ],
    [ "memory::sparse_array< T, Key, chunks_size >", "classmemory_1_1sparse__array.html", null ],
    [ "core::ivk::shader::specialization", "structcore_1_1ivk_1_1shader_1_1specialization.html", null ],
    [ "psl::static_ring_array< T, N >", "classpsl_1_1static__ring__array.html", null ],
    [ "core::stream", "classcore_1_1stream.html", null ],
    [ "core::os::surface", "classcore_1_1os_1_1surface.html", null ],
    [ "core::ivk::swapchain", "classcore_1_1ivk_1_1swapchain.html", null ],
    [ "core::ivk::texture_t", "classcore_1_1ivk_1_1texture__t.html", null ],
    [ "utility::debug::trace_info", "structutility_1_1debug_1_1trace__info.html", null ],
    [ "psl::UID", "structpsl_1_1_u_i_d.html", null ],
    [ "psl::format::validator", "classpsl_1_1format_1_1validator.html", null ],
    [ "psl::view_ptr< T >", "classpsl_1_1view__ptr.html", null ],
    [ "psl::view_ptr< core::gfx::drawpass >", "classpsl_1_1view__ptr.html", null ],
    [ "psl::view_ptr< core::gfx::render_graph >", "classpsl_1_1view__ptr.html", null ],
    [ "psl::view_ptr< core::resource::cache_t >", "classpsl_1_1view__ptr.html", null ],
    [ "psl::view_ptr< psl::ecs::state_t >", "classpsl_1_1view__ptr.html", null ],
    [ "psl::view_ptr< psl::meta::file >", "classpsl_1_1view__ptr.html", null ],
    [ "psl::view_ptr< psl::spmc::producer< psl::view_ptr< details::packet > > >", "classpsl_1_1view__ptr.html", null ],
    [ "psl::view_ptr< psl::spmc::producer< T > >", "classpsl_1_1view__ptr.html", null ],
    [ "psl::view_ptr< scheduler >", "classpsl_1_1view__ptr.html", null ],
    [ "core::data::window", "classcore_1_1data_1_1window.html", null ]
];