name: deploy cloudflare pages

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm i
    - run: npm run build --if-present
    - name: Publish
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
        command: pages publish "." --project-name=paradigmengine.dev --branch=main
