name: Documentation

on: workflow_dispatch

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup Doxygen
      run: |
        curl -fsSL -o ../doxygen.tar.gz "https://www.doxygen.nl/files/doxygen-1.9.5.linux.bin.tar.gz"
        tar -xzf ../doxygen.tar.gz --directory ../
        sudo cp -a ../doxygen-1.9.5/bin/doxy* /usr/local/bin
    - name: Update Python
      run: pip3 install jinja2 Pygments
    - name: Generate
      run: python3 .github/generate.py --verbose
    - name: Publish
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git diff --exit-code --quiet || (git add -A && git commit -m "Documentation update" && git push)
